import { Option } from "../types/propes.types";



export const Certificate_Of_competency_grade: Option[] = [
    { label: "Master -  II/2", value: "Master -  II/2" },
    { label: "Chief Officer -  II/2", value: "Chief Officer -  II/2" },
    { label: "2nd Officer-  II/1", value: "2nd Officer-  II/1" },
    { label: "3rd Officer -  II/1", value: "3rd Officer -  II/1" },
    { label: "Chief Engineer -  III/2", value: "Chief Engineer -  III/2" },
    { label: "2nd Engineer -  III/2", value: "2nd Engineer -  III/2" },
    { label: "3rd Engineer -  III/1", value: "3rd Engineer -  III/1" },
    { label: "4th Engineer -  III/1", value: "4th Engineer -  III/1" },
    { label: "Electro-technical officer -  III/6", value: "Electro-technical officer -  III/6" },
    { label: "GMDSS - IV/2", value: "GMDSS - IV/2" },
    { label: "AB -  II/4 (WK)", value: "AB -  II/4 (WK)" },
    { label: "AB -  II/5 (COP)", value: "AB -  II/5 (COP)" },
    { label: "OILER -  III/4 (WK)", value: "OILER -  III/4 (WK)" },
    { label: "OILER -  III/5 (COP)", value: "OILER -  III/5 (COP)" },
    { label: "Cook - Regulation 3.2 & of the MLC, 2006.", value: "Cook - Regulation 3.2 & of the MLC, 2006." },

]


export const Flag_endorsement_name: Option[] = [
    { label: "COC endorsements: COE", value: "COC endorsements: COE" },
    { label: "GOC endorsement", value: "GOC endorsement" },
    { label: "Security course endorsement", value: "Security course endorsement" },
    { label: "Oil tanker  endorsements", value: "Oil tanker  endorsements" },
    { label: "Chemical tankers endorsements", value: "Chemical tankers endorsements" },
    { label: "Gas carriers endorsements", value: "Gas carriers endorsements" },

]


export const Dangerous_cargo_endorsement_name: Option[] = [
    { label: "Oil tanker  endorsements    ", value: "Oil tanker  endorsements    " },
    { label: "Chemical tankers endorsements", value: "Chemical tankers endorsements" },
    { label: "Gas carriers endorsements", value: "Gas carriers endorsements" },
]

let certificate_name_data = ["6G CERTIFICATE",
    "ADVANCED FIRE FIGHTING",
    "ADVANCED TANKER TRAINING (OIL)",
    "ADVANCED TRAINING FOR CHEMICAL TANKER CARGO OPERATIONS",
    "ATOTCO(ADVANCED TRAINING FOR OIL TANKER CARGO OPERATIONS)",
    "AUTOMATIC RADAR PLOTTING AIDS",
    "BACHELOR DEGREE",
    "BASIC OIL & CHEMICAL TANKER OPERATIONS",
    "BASIC SAFETY TRAINING (SOLAS)",
    "BASIC SAFETY TRAINING (SOLAS) - REFRESHER COURSE",
    "BASIC SAFETY TRAINING AND INSTRUCTION",
    "BOSIET",
    "BRIDGE RESOURCES MANAGEMENT",
    "BRIDGE TEAM AND RESOURCE MANAGEMENT",
    "BTOCT (BASIC TRAINING FOR OIL AND CHEMICAL TANKER)",
    "CARGO AND BALLAST HANDLING ",
    "CARRIAGE OF DANGEROUS AND HAZARDOUS SUBSTANCES ",
    "CCMC CERT ",
    "CERTIFICATE OF PROFICIENCY ",
    "CHEMICAL TANKER FAMILIARIZATION (CTF) ",
    "CHEMICAL TANKER SPECIALISED TRAINING PROGRAMME ",
    "CHEMICAL TANKERS CARGO & BALLAST HANDLING ",
    "CHEMICAL TANKERS OPERATION & MAINTENANCE OF INERT GAS SYSTEM ",
    "COMPETENCE UPDATING COURSE ",
    "COOKERY CERTIFICATE ",
    "COP ",
    "CRANE OPERATOR ",
    "CRISIS MANAGEMENT AND HUMAN BEHAVIOR ",
    "CROWD MANAGEMENT ",
    "CRUDE OIL WASHING ",
    "DANGEROUS CARGO HANDLING ",
    "DYNAMIC POSITIONING (ADVANCED) DPA ",
    "DYNAMIC POSITIONING (FULL) DPO LIMITED ",
    "DYNAMIC POSITIONING (FULL) DPO UNLIMITED ",
    "EFFICIENT ENGINE ROOM RATING (EER) ",
    "ELECTRICAL INSTALLATION",
    "ELECTRONIC CHART DISPLAY AND INFORMATION SYSTEMS (ECDIS) ",
    "ELEMENTARY FIRST AID (EFA) ",
    "ENGINE RESOURCE MANAGEMENT ",
    "ENGINE ROOM RESOURCES MANAGEMENT ",
    "ENGINE ROOM SIMULATOR ",
    "ENGINE ROOM TEAM MANGEMENT ",
    "FAST RESCUE BOATS ",
    "FIRE PREVENTION & FIRE FIGHTING (FPFF) ",
    "FOOD HANDLING CERTIFICATE ",
    "FITTER GENERAL ",
    "GENERAL PURPOSE RATING ",
    "GENERAL TANKER FAMILIARIZATION ",
    "GMDSS (GOC) ",
    "GMDSS OPERATOR ROC ",
    "GP CERT. ",
    "H2S/BA ",
    "HAZMAT ",
    "HIGH VOLTAGE EQUIPMENT ",
    "ICE NAVIGATION ",
    "INERT GAS SYSTEM ",
    "INTERNATIONAL SAFETY MANAGEMENT CODE ",
    "ISM CODE ",
    "JRC ECDIS ",
    "LARGE VESSELS HANDLING ",
    "LIQUIFIED CARGO HANDLING SIMULATOR(LCHS) ",
    "LIQUIFIED GAS TANKER FAMILIARIZATION (LGTF) ",
    "LOADING CONTROL SYSTEM",
    "MAINTENANCE OF ELECTRICAL AND ELECTRONIC EQUIPMENT ",
    "MARITIME ENGLISH ",
    "MEDICAL CARE ",
    "MEDICAL CARE ON BOARD SHIP (LIMITED) ",
    "MEDICAL CARE ON BOARD SHIP (UNLIMITED) ",
    "MEDICAL FIRST AID ",
    "NAVIGATION AND WATCH KEEPING ",
    "NAVIGATION BRIDGE TEAMWORK (MANAGEMENT) ",
    "NAVIGATION BRIDGE TEAMWORK (OPERATIONAL) ",
    "NAVIGATION BRIDGE TEAMWORK (SUPPORT) ",
    "NORWEGIAN PILOT EXEMPTION ",
    "OIL DCE (DANGEROUS CARGO ENDORSEMENT) ",
    "OIL SPILL CONTROL COURSE ",
    "OIL TANKER FAMILIARISATION (OTF) ",
    "OIL TANKER SPECIALIZED TRAINING PROGRAM ",
    "OIL TANKERS OPERATION & MAINTENANCE OF INERT GAS SYSTEMS ",
    "OLF/OPITO/NOGEPA ",
    "OPT ",
    "P/M CERTIFICATE ",
    "PERSONAL SAFETY & SOCIAL RESPONSIBILITIES (PSSR) ",
    "PERSONAL SURVIVAL TECHNIQUES (PST) ",
    "POLUTION PREVENTION DUTIES ",
    "PROFICIENCY IN FAST RESCUE BOAT ",
    "RADAR OBESERVER COURSE ",
    "RADAR OBSERVATION, PLOTTING AND AUTOMATIC RADAR PLOTTING AIDS (ARPA) ",
    "RADAR SIMULATOR ",
    "SHIP PERSONNEL HAVING SPECIFIC DUTIES ON THE PROGRAM ",
    "SHIP SECURITY OFFICER ",
    "SHIPBOARD SAFETY OFFICER ",
    "SHORE-BASED FIRE FIGHTING",
    "RADAR, ARPA, BRIDGE TEAM WORK AND SEARCH AND RESCUE ",
    "RISK ASSESSMENT ",
    "RISK MANAGEMENT & INCIDENT INVESTIGATION ",
    "RO-RO PASSENGER SHIPS FAMILIARIZATION (CROWD & CRISES MANAGEMENT) (PSF) ",
    "SAFETY MANAGEMENT SYSTEM ",
    "SDP MAINTENANCE COURSE ",
    "SEARCH AND RESCUE OPERATIONS (MANAGEMENT) ",
    "SEARCH AND RESCUE OPERATIONS (OPERATIONAL) ",
    "SEARCH AND RESCUE OPERATIONS (SUPPORT) ",
    "SECURITY FAMILIARIZATION (ISPS CODE) ",
    "STCW BASIC TRAINING  ",
    "SECURITY TRAINING FOR SEAFERERS WITH DESIGNATED SECURITY DUTIES ",
    "SHIELDED METAL ARC WELDING II ",
    "SHIP HANDLING SIMULATOR	",
    "TANKER FAMILIARIZATION ",
    "TANKER FAMILIARIZATION (CHEMICAL) ",
    "TANKER FAMILIARIZATION (GAS) ",
    "TANKER FAMILIARIZATION (OIL) ",
    "TANKER FAMILIARIZATION (OIL, GAS AND CHEMICAL TANKERS) ",
    "THEORETICAL,PRACTICAL & SIMULATING TRAINING USING AIS ",
    "TRAINING FOR RO-RO PASSANGER SHIPS PERSONNEL ",
    "WELDING CERTIFICATE"];

export const certificate_name: Option[] =  certificate_name_data.map((item) => ({
    label: item,
    value: item,
  }));